### PR TITLE
Make Istio uniformly consumable

### PR DESCRIPTION
**Pull request by scothis**
Istio is now optional for both the Core and Knative runtimes. Without
Istio, ingress will not be provided for Knative. For the Core Runtime
ingress can now be provided via Istio.

In theory, this will also make it easier to switch to a different
ingress controller as Knative installs will no longer presume Istio.

### CODE REVIEW

**Comment by scothis** [comment]
This is an alternative to #109

**Comment by andrew-su** [comment]
I don't think either of the PRs will help with what we're trying to achieve right now. There is more to just enabling the autogenerated gateway to support ingress -> routeability.

**Comment by scothis** [comment]
> Minor comment about knative install requirements. As of today istio is a requirement so I am not sure about instructions saying its optional. Rest everything looks good.

Yea, I was a bit too optimistic here. A L7 provider is required in order for the weighted routing to work. With this change, we'd no longer assume that is Istio, but at the same time, Istio is the only option.

**Comment by scothis** [comment]
stale

**Pull request closed without merging**
